---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# gedsb

<!-- badges: start -->
<!-- badges: end -->

The goal of the `gedsb` package is to provide the visual identity ggplot2 theme for charts and tables. 

## Installation

You can install the development version of gedsb from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("grousell/gedsb")
```

## Example

By loading the package the theme is automatically set. 

```{r example}
library(gedsb)
library (ggplot2)
library (dplyr)

basic_plot <- mtcars |>
  group_by (cyl) |>
  count () |>
  mutate (cyl = factor (cyl)) |>
  ggplot(aes (x = cyl, y = n)) +
  geom_col() + 
  labs(
    title = "Number of Cars by Cylinders",
    x = "Cylinders",
    y = "Number of Cars"
  ) 

basic_plot

basic_plot + 
  gedsb_bar_plot_theme()

```

GEDSB colors and fonts are loaded with the `gedsb_colours_fonts` function. 

```{r}
gedsb_colours_fonts()

plot_colored <- mtcars |>
  group_by (cyl) |>
  count () |>
  mutate (cyl = factor (cyl)) |>
  ggplot(ggplot2::aes (x = cyl, y = n)) +
  geom_col(fill = gedsbBlue) + # Colour added here
  labs(
    title = "Number of Cars by Cylinders",
    x = "Cylinders",
    y = "Number of Cars"
  ) +
  gedsb_bar_plot_theme()

plot_colored

```

